name: Trigger auto deployment for first-container-13

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/first-container-13-AutoDeployTrigger-5e53d432-fb1c-4e89-b56e-6d813fc8f401.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FIRSTCONTAINER13_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FIRSTCONTAINER13_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FIRSTCONTAINER13_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: imagepulldocker.azurecr.io
          registryUsername: ${{ secrets.FIRSTCONTAINER13_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FIRSTCONTAINER13_REGISTRY_PASSWORD }}
          containerAppName: first-container-13
          resourceGroup: NewGroup
          imageToBuild: imagepulldocker.azurecr.io/first-container-13:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


